#!/bin/bash

# Clear terminal window
clear

global_setup() {
  # Setup present working directory
  dir=$(pwd)
  echo $dir
}

gradlew_util() {
  # Print gradle task execution logs
  if ./gradlew $1; then
    echo $2
  else
    echo $3
    exit 1
  fi
}

do_clean() {
  # Clean project
  gradlew_util clean "Project Cleaned successfully" "Project Cleaned Failed"
  # Delete libs folder
  rm -rf $dir/app/libs
}

run_unit_tests() {
  # Run unit tests
  gradlew_util :identitylibrary:testReleaseUnitTest "Unit Tests passed" "Unit Tests failed"
}

build() {
  # Build release version of CyberArk Identity SDK
  gradlew_util :identitylibrary:assembleRelease "CyberArk Identity SDK Release binary Built Successfully" "CyberArk Identity SDK Release binary Built failed"
}

global_setup
do_clean
run_unit_tests
build